# Generated by Django 5.0.1 on 2025-11-05 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_fcfa', models.DecimalField(decimal_places=2, help_text='Taux de change: 1 USD = X FCFA', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Taux de Change',
                'verbose_name_plural': 'Taux de Change',
                'db_table': 'exchange_rates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_method', models.CharField(choices=[('air_rapide', 'Aérien Rapide'), ('air_express', 'Aérien Express'), ('sea_no_motor', 'Maritime sans Moteur'), ('sea_with_motor', 'Maritime avec Moteur')], help_text='Type de transport', max_length=20, unique=True)),
                ('rate_per_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Tarif par kilogramme (pour transport aérien, en FCFA)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rate_per_m3', models.DecimalField(blank=True, decimal_places=2, help_text='Tarif par mètre cube (pour transport maritime, en FCFA)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_days', models.IntegerField(help_text='Délai minimum de livraison en jours', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_days', models.IntegerField(help_text='Délai maximum de livraison en jours', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarif Logistique',
                'verbose_name_plural': 'Tarifs Logistiques',
                'db_table': 'logistics_rates',
                'ordering': ['shipping_method'],
            },
        ),
    ]
