# Generated by Django 5.0.1 on 2025-11-06 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_exchangerate_logisticsrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quote', to='api.order'),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Non payé'), ('paid', 'Payé')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix du devis en USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
