# Generated by Django 5.0.1 on 2026-02-09 12:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrate_is_active_to_status(apps, schema_editor):
    Product = apps.get_model('api', 'Product')
    Product.objects.filter(is_active=True).update(status='active')
    Product.objects.filter(is_active=False).update(status='unavailable')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_category_options_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('promotion', 'En Promotion'), ('unavailable', 'Indisponible')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.supplier'),
        ),
        migrations.RunPython(migrate_is_active_to_status, migrations.RunPython.noop),
    ]
