# Generated by Django 5.0.1 on 2026-02-12 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_product_status_oldprice_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_price_fcfa',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='price_fcfa',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
