# Generated by Django 5.0.1 on 2026-02-12 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_price_fcfa_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marketing_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix marketing barre ($)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='product',
            name='marketing_price_fcfa',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Prix marketing barre (FCFA)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
