# Generated by Django 5.0.1 on 2026-02-12 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_marketing_price_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='marketing_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='marketing_price_fcfa',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Prix marketing barre en rouge (FCFA)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
