# Generated by Django 5.0.1 on 2026-02-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_marketing_price_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('quoted', 'Devis envoyé'), ('confirmed', 'Confirmée'), ('paid', 'Payée'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
