# Generated by Django 5.0.1 on 2026-02-12 13:33

from django.db import migrations, models
from decimal import Decimal


def migrate_existing_orders(apps, schema_editor):
    """Convertir les commandes existantes : USD→FCFA, anciens statuts→pending"""
    Order = apps.get_model('api', 'Order')
    OrderItem = apps.get_model('api', 'OrderItem')
    Payment = apps.get_model('api', 'Payment')
    rate = Decimal('621')

    for order in Order.objects.all():
        # Convertir montants USD → FCFA
        order.total = round(order.total * rate)
        order.paid_amount = round(order.paid_amount * rate)
        order.shipping_fee = round(order.shipping_fee * rate)
        # Mapper anciens statuts
        if order.status in ('quoted', 'confirmed'):
            order.status = 'pending'
        # Mapper anciens shipping_method
        if order.shipping_method in ('air_rapide', 'air_express'):
            order.shipping_method = 'avion'
        elif order.shipping_method in ('sea_no_motor', 'sea_with_motor'):
            order.shipping_method = 'bateau'
        else:
            order.shipping_method = 'bateau'
        # Remplir les nouveaux champs
        order.payment_mode = 'total'
        order.amount_due = order.total
        order.save()

    for item in OrderItem.objects.all():
        item.price = round(item.price * rate)
        item.save()

    for payment in Payment.objects.all():
        payment.amount = round(payment.amount * rate)
        payment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_order_quoted_paid_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_due',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('partial', 'Partiel (70%)'), ('total', 'Total (100%)')], default='total', max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivery_mode',
            field=models.CharField(choices=[('bateau', 'Bateau'), ('avion', 'Avion')], default='bateau', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('bateau', 'Bateau'), ('avion', 'Avion'), ('mixte', 'Mixte')], default='bateau', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('wave', 'Wave'), ('mobile_money', 'Mobile Money'), ('cash', 'Espèces')], max_length=20),
        ),
        migrations.RunPython(migrate_existing_orders, migrations.RunPython.noop),
    ]
