# Generated by Django 5.0.1 on 2026-02-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_redesign_order_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
