# Generated by Django 5.0.1 on 2026-02-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_color_to_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé en préparation'), ('shipped', 'Expédié'), ('available', 'Disponible à Abidjan'), ('delivered', 'Livré'), ('cancelled', 'Annulée')], default='pending', max_length=20),
        ),
    ]
